### ISSUE TITLE
fix: Window resizing does not work as expected.

### ISSUE THREAD

**Issue by lindorffs** [coderloff/ferx#11]
## The Issue:
- When the window is resized, it is possible for the center of the scene buffer to be off center from the ImGui display element.
### What is expected?
- When the window is resized, the center of the scene buffer should remain centered in the ImGui display element.

![image](https://github.com/user-attachments/assets/b2d925a8-0248-47d3-b7eb-5aef6830d395)

Possible Fix:
- Set a "WindowSizeCallback" which recreates the buffers. This is likely an ugly, dirty approach, but it works.
- Set this callback in Renderer::Init()
```c++
Renderer.cpp
...
void Renderer::Init() {

	...

	glfwSetWindowSizeCallback(Engine::Get().GetWindow().GetWindow(), [](GLFWwindow* window, int width, int height)
	{
		SetupBuffers();
	});
}
```
- The GetWidth() and GetHeight() functions do not actually reflect the current window size. Use ``glfwGetWindowSize`` to retrieve the current size.
```c++
Window.cpp
...
int Window::GetWidth() const
{
	int width, height;
	glfwGetWindowSize(m_Window, &width, &height);
	return width;
}

int Window::GetHeight() const
{
	int width, height;
	glfwGetWindowSize(m_Window, &width, &height);
	return height;
}
```
![image](https://github.com/user-attachments/assets/5540de85-9d8b-4036-93a1-301831208c7e)

**Comment by lindorffs** [comment]
Looks good! Your approach also introduces a way to eliminate the need to call `glfwGetWindowSize()` more than once.

**Comment by ismayilovh** [comment]
> Looks good! Your approach also introduces a way to eliminate the need to call `glfwGetWindowSize()` more than once.

Thanks again for your great contributions and kind words! That's right; I wanted to improve performance with this approach.
